### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by angustrau** [jumptrading/luddite#6]
Hi there! I'm having trouble running the test suite for this package. I'm running the tests under Python 3.8 on Linux. I have attached the logs. Any help would be appreciated!
[tests.log](https://github.com/jumptrading/luddite/files/6823168/tests.log)

**Comment by wimglenn** [comment]
Thanks for the notification.  More recent version of setuptools changed how they parse requirements.txt files, resulting in a different kind of exception encountered.

Fixed by https://github.com/jumptrading/luddite/pull/7

**Comment by angustrau** [comment]
Thanks for the fix! Would you be able to push a github/pypi release with this?

**Comment by wimglenn** [comment]
@angustrau  done.
